refactor mapItem on CollectionViewer
azvyae/dokunext pull request #14
Opened 2023-07-16 06:05 UTC by edwinbernadus

just refactoring some codes on CollectionViewer

2023-07-16 06:07 UTC, edwinbernadus commented
follow up from https://github.com/azvyae/dokunext/issues/11

2023-07-16 14:50 UTC, azvyae requested changes

2023-07-16 14:50 UTC, azvyae commented on src/app/postman/[collections]/extractData.ts
Keep in mind that this is NextJS with App router structure.

Instead of creating `extractData.ts` and `mapItem.ts` file that essentially service/actions logic for each `extractData()` and `mapItem()` function, you can put both functions in one file `services.ts` and use named export on the end of the file:

```typescript
export {extractData, mapItem}
```

2023-07-16 14:50 UTC, azvyae commented on src/fetcher/getCollection.ts
I know that this file extracting fetch function from /[collections]/page.tsx. Just like my first comment, instead of separating it to fetcher/getCollection.ts file, you can put it in one service.ts file inside that `app/postman/[collection]` folder, because this function/service only used on the `app/postman/[collection]/page.tsx` file.

2023-07-17 05:34 UTC, edwinbernadus commented
ok got it. 
thx u for the great review sir

will fix that (but not soon)
slow mode lol, 

this is Monday. 
lots to do at my office

2023-07-20 16:11 UTC, azvyae approved these changes
Thanks for helping me maintain this project

2023-07-20 16:11 UTC, merged